Repository mabemoreira/LearningPath, pull requests merged in 2024-09, with the labels that each got.

#15 Configuracoes do ambiente
  .gitignore
  README.md
  backend/.pre-commit-config.yaml
  backend/README.md
  backend/alembic.ini
  backend/requirements.txt
  backend/src/__init__.py
  backend/src/__main__.py
  backend/src/alembic/README
  backend/src/alembic/env.py
  backend/src/alembic/script.py.mako
  backend/src/configurations/__init__.py
  backend/src/configurations/database.py
  backend/src/configurations/secrets.py
  backend/src/controllers/__init__.py
  backend/src/exceptions/__init__.py
  backend/src/exceptions/secrets_exceptions.py
  backend/src/models/__init__.py
  backend/src/models/user_model.py
  backend/src/services/__init__.py
  backend/src/tests/__init__.py
  frontend/.editorconfig
  frontend/.vscode/extensions.json
  frontend/.vscode/launch.json
  frontend/.vscode/tasks.json
  frontend/README.md
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
  frontend/src/app/app.routes.ts
  frontend/src/index.html
  frontend/src/main.ts
  frontend/src/styles.css
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.spec.json
Labels: environment

#23 Setup backend
  .gitignore
  backend/.vscode/launch.json
  backend/README.md
  backend/alembic.ini
  backend/requirements.txt
  backend/src/__init__.py
  backend/src/__main__.py
  backend/src/alembic/README
  backend/src/alembic/env.py
  backend/src/alembic/script.py.mako
  backend/src/asgi.py
  backend/src/configurations/database.py
  backend/src/configurations/secrets.py
  backend/src/configurations/settings.py
  backend/src/configurations/urls.py
  backend/src/controllers/user_controller.py
  backend/src/manage.py
  backend/src/models/__init__.py
  backend/src/models/user_model.py
  backend/src/tests/test_user_controller.py
  backend/src/wsgi.py
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/data.service.ts
  frontend/src/main.ts
Labels: environment

#25 Feature/homepage
  .gitignore
  frontend/.vscode/launch.json
  frontend/README.md
  frontend/angular.json
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
  frontend/src/app/app.module.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/data.service.ts
  frontend/src/app/features/login/homepage/homepage.component.css
  frontend/src/app/features/login/homepage/homepage.component.html
  frontend/src/app/features/login/homepage/homepage.component.spec.ts
  frontend/src/app/features/login/homepage/homepage.component.ts
  frontend/src/app/features/login/layout/footer/footer.component.css
  frontend/src/app/features/login/layout/footer/footer.component.html
  frontend/src/app/features/login/layout/footer/footer.component.spec.ts
  frontend/src/app/features/login/layout/footer/footer.component.ts
  frontend/src/app/features/login/layout/header/header.component.css
  frontend/src/app/features/login/layout/header/header.component.html
  frontend/src/app/features/login/layout/header/header.component.spec.ts
  frontend/src/app/features/login/layout/header/header.component.ts
  frontend/src/app/features/login/product-page/product-page.component.css
  frontend/src/app/features/login/product-page/product-page.component.html
  frontend/src/app/features/login/product-page/product-page.component.spec.ts
  frontend/src/app/features/login/product-page/product-page.component.ts
  frontend/src/app/features/login/team-page/team-page.component.css
  frontend/src/app/features/login/team-page/team-page.component.html
  frontend/src/app/features/login/team-page/team-page.component.spec.ts
  frontend/src/app/features/login/team-page/team-page.component.ts
  frontend/src/assets/logo.svg
  frontend/src/environments/environment.ts
  frontend/src/index.html
  frontend/src/main.ts
  frontend/src/styles.css
Labels: enhancement

#28 Implementação da deleção de usuário
  .github/workflows/angular-build.yml
  .github/workflows/django-build.yml
  .github/workflows/django-tests.yml
  .gitignore
  backend/.pre-commit-config.yaml
  backend/.vscode/launch.json
  backend/.vscode/settings.json
  backend/README.md
  backend/src/configurations/settings.py
  backend/src/configurations/urls.py
  backend/src/controllers/custom_user_controller.py
  backend/src/exceptions/response_exceptions.py
  backend/src/manage.py
  backend/src/services/custom_user_service.py
  backend/src/tests/__init__.py
  backend/src/tests/test_user_controller.py
  backend/src/tests/test_user_service.py
  backend/test.env
Labels: enhancement, Atividade 2

#27 Leitura usuário
  backend/src/controllers/custom_user_controller.py
  backend/src/services/custom_user_service.py
  backend/src/tests/test_user_service.py
Labels: enhancement, Atividade 2
